#include "mapreduce.h"

int main(int argc, char *argv[]) {
	
	if(argc < 4) {
		printf("Less number of arguments.\n");
		printf("./mapreduce #mappers #reducers inputFile\n");
		exit(0);
	}

	// ###### DO NOT REMOVE ######
	int nMappers 	= strtol(argv[1], NULL, 10);
	int nReducers 	= strtol(argv[2], NULL, 10);
	char *inputFile = argv[3];

	// ###### DO NOT REMOVE ######
	bookeepingCode();

	// ###### DO NOT REMOVE ######
	pid_t pid = fork();
	if(pid == 0){
		//send chunks of data to the mappers in RR fashion
		sendChunkData(inputFile, nMappers);
		exit(0);
	}
	sleep(1);


	// To do
	// spawn mappers processes and run 'mapper' executable using exec
	for (int i = 1; i <= nMappers; i++) {
		pid_t pid = fork();

		if (pid < 0) {
			perror("Fork failed.");
			return 1;
		}

		//If child
		if (pid == 0) {
			char id[10];
			sprintf(id, "%d", i); //Making the id a string to be passed below
			int ret = execl("mapper", "mapper", id, NULL); //Create mapper

			if (ret) {
				perror("Map failed");
				exit(-1);
			}
			exit(0);
		}
	}
	//printf("Finished making mappers\n");
	// To do
	// wait for all children to complete execution
    for (int i = 1; i <= nMappers; i++) {
		wait(NULL);
	}
	//printf("Mappers finished\n");
	// ###### DO NOT REMOVE ######
    // shuffle sends the word.txt files generated by mapper 
    // to reducer based on a hash function
	pid = fork();
	if(pid == 0){
		shuffle(nMappers, nReducers);
		exit(0);
	}
	sleep(1);
	//printf("Finished shuffling\n");

	// To do
	// spawn reducer processes and run 'reducer' executable using exec
	for (int i = 1; i <= nReducers; i++) {
		pid_t pid = fork();

		if (pid < 0) {
			perror("Fork failed.");
			return 1;
		}

		//If child
		if (pid == 0) {
			char id[10];
			sprintf(id, "%d", i); //Making the id a string to be passed below
			int ret = execl("reducer", "reducer", id, NULL); //Create reducer

			if (ret) {
				perror("Reduce failed.");
				exit(-1);
			}
			exit(0);
		}
	}
	//printf("Finished making reducers\n");
	
	// To do
	// wait for all children to complete execution
	for (int i = 1; i <= nReducers; i++) {
		wait(NULL);
	}
	//printf("Reducers finished\n");


	return 0;
}